In [15]:
import pandas as pd
import numpy as np
df = pd.read_csv("Bangladesh_database_Final_Merged.csv")

df.head()

,FPAR,Avg_Salinity_Index,EVI,Rain_Temp_Ratio,Rainfall,Wind_Mean,Temp_Min,Wind_Max,Temp_Max,District,...,Avg Humidity,Heat_Stress_Days,Silt,Growth,CN_Ratio,Crop Name,Organic_Carbon,Transplant,Season,NDVI_Season_Mean
0,6.314995,560.494023,0.311631,11.23,220.43,1.452917,8.35,4.33,30.58,Bagerhat,...,55.0,0,49.52,Jan to March,8.73,Wheat,33.97,Dec,Rabi,0.511809
1,6.314995,560.494023,0.311631,11.23,220.43,1.452917,8.35,4.33,30.58,Bagerhat,...,60.0,0,49.52,Jan to March,8.73,Maize 2,33.97,Dec,Rabi,0.511809
2,6.314995,560.494023,0.311631,11.23,220.43,1.452917,8.35,4.33,30.58,Bagerhat,...,72.5,0,49.52,Dec to March,8.73,Boro,33.97,Nov,Rabi,0.511809
3,6.314995,560.494023,0.311631,11.23,220.43,1.452917,8.35,4.33,30.58,Bagerhat,...,80.0,0,49.52,Dec to March,8.73,Sweet Potato,33.97,Nov,Rabi,0.511809
4,4.169442,883.021928,0.308177,22.73,656.33,2.481885,16.01,5.86,41.26,Bagerhat,...,70.0,54,49.52,No need to do,8.73,Mango,33.97,April,Kharif 1,0.267147

In [16]:
print("KIỂU DỮ LIỆU TỪNG CỘT")
print(df.dtypes)
print()
print("THỐNG KÊ MÔ TẢ (CỘT SỐ)")
df.describe()

KIỂU DỮ LIỆU TỪNG CỘT
FPAR                     float64
Avg_Salinity_Index       float64
EVI                      float64
Rain_Temp_Ratio          float64
Rainfall                 float64
Wind_Mean                float64
Temp_Min                 float64
Wind_Max                 float64
Temp_Max                 float64
District                     str
Clay                     float64
LAI                      float64
Nitrogen                 float64
Soil_Moisture_mm         float64
pH                       float64
LST_Kelvin               float64
Dominant_Soil_Texture        str
AP Ratio                     str
Temp_Mean                float64
Avg Humidity             float64
Heat_Stress_Days           int64
Silt                     float64
Growth                       str
CN_Ratio                 float64
Crop Name                    str
Organic_Carbon           float64
Transplant                   str
Season                       str
NDVI_Season_Mean         float64
dtype: object

THỐNG KÊ MÔ TẢ (CỘT SỐ)

,FPAR,Avg_Salinity_Index,EVI,Rain_Temp_Ratio,Rainfall,Wind_Mean,Temp_Min,Wind_Max,Temp_Max,Clay,...,Soil_Moisture_mm,pH,LST_Kelvin,Temp_Mean,Avg Humidity,Heat_Stress_Days,Silt,CN_Ratio,Organic_Carbon,NDVI_Season_Mean
count,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,...,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000,4608.000000
mean,4.651780,807.549030,0.344988,31.837630,876.246892,1.979604,14.763767,6.254019,34.932587,33.150781,...,18.880246,5.830469,300.825615,25.685662,71.597222,13.282118,40.247344,10.835781,20.655156,0.373663
std,0.936640,146.335540,0.067935,21.745887,615.649481,0.674624,4.285904,1.849613,4.145008,3.546139,...,6.112914,0.249272,1.738097,3.949108,11.245552,22.313342,5.009566,1.899242,5.125279,0.107158
min,2.105833,451.410437,0.114085,3.500000,64.710000,0.072195,7.090000,0.510000,28.880000,25.820000,...,8.551960,5.390000,297.138773,17.974917,35.000000,0.000000,28.930000,6.960000,12.120000,-0.001671
25%,4.059624,710.150645,0.306481,10.370000,208.710000,1.452917,9.620000,5.100000,30.900000,30.497500,...,12.282738,5.640000,299.256991,20.408583,67.500000,0.000000,37.160000,9.505000,17.012500,0.305881
50%,4.669083,788.540754,0.334596,35.290000,984.860000,2.061707,15.500000,6.320000,34.220000,32.575000,...,19.295412,5.775000,301.290109,27.768699,72.500000,0.000000,39.300000,10.720000,19.945000,0.389344
75%,5.198117,914.318080,0.386841,45.390000,1278.220000,2.389512,18.340000,7.370000,37.590000,35.997500,...,25.297660,5.967500,302.012443,28.147724,80.000000,17.000000,42.840000,12.102500,23.460000,0.441558
max,7.518121,1211.038878,0.594884,120.010000,3216.480000,4.176393,24.880000,12.920000,44.700000,40.330000,...,25.382592,6.470000,304.438744,30.546885,90.000000,96.000000,52.350000,16.110000,33.970000,0.695371

In [17]:
print("THỐNG KÊ CỘT CATEGORICAL")
cat_cols = ['District', 'Dominant_Soil_Texture', 'AP Ratio',
            'Growth', 'Crop Name', 'Transplant', 'Season']
 
for col in cat_cols:
    print(f" [{col}] — {df[col].nunique()} giá trị duy nhất")
    print(df[col].value_counts().head(5).to_string())

THỐNG KÊ CỘT CATEGORICAL
 [District] — 64 giá trị duy nhất
District
Bagerhat     72
Bandarban    72
Barguna      72
Barishal     72
Bhola        72
 [Dominant_Soil_Texture] — 2 giá trị duy nhất
Dominant_Soil_Texture
Loamy (Thịt/Phù sa)    4536
Clayey (Sét)             72
 [AP Ratio] — 3893 giá trị duy nhất
AP Ratio
#DIV/0!    416
1           19
2           19
0.5         16
0           13
 [Growth] — 32 giá trị duy nhất
Growth
No need to do     640
Nov to March      384
June to August    320
Oct to Nov        320
Nov to Feb        256
 [Crop Name] — 73 giá trị duy nhất
Crop Name
Wheat           64
Maize 2         64
Boro            64
Sweet Potato    64
Mango           64
 [Transplant] — 19 giá trị duy nhất
Transplant
April    838
Oct      768
Sep      704
March    454
June     453
 [Season] — 3 giá trị duy nhất
Season
Kharif 2    1792
Kharif 1    1536
Rabi        1280

In [18]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
 
missing_df = pd.DataFrame({
    'Số lượng NaN': missing,
    'Tỷ lệ (%)': missing_pct
})
 
print("=== KIỂM TRA GIÁ TRỊ NULL ===")
print(missing_df[missing_df['Số lượng NaN'] > 0])
 
if missing.sum() == 0:
    print("\n KHÔNG có giá trị null thực sự trong dataset")

=== KIỂM TRA GIÁ TRỊ NULL ===
Empty DataFrame
Columns: [Số lượng NaN, Tỷ lệ (%)]
Index: []

 KHÔNG có giá trị null thực sự trong dataset

In [19]:
n_dup = df.duplicated().sum()
print(f"Số hàng trùng lặp: {n_dup}")
 
if n_dup > 0:
    print("\\n--- Các hàng bị trùng ---")
    print(df[df.duplicated(keep=False)])
    df = df.drop_duplicates()
    print(f"\n Đã xoá xong. Kích thước mới: {df.shape}")
else:
    print(" Không có hàng nào trùng lặp!")

Số hàng trùng lặp: 0
 Không có hàng nào trùng lặp!

In [20]:
print(f"Kiểu dữ liệu: {df['AP Ratio'].dtype}")  

 
failed_mask = pd.to_numeric(df['AP Ratio'], errors='coerce').isnull()
print(f"Số giá trị không convert được: {failed_mask.sum()}")
print("Các giá trị lỗi:")
print(df[failed_mask]['AP Ratio'].value_counts())
#Vấn đề: Cột `AP Ratio` đang là kiểu `str` và có 416 giá trị `#DIV/0!` (lỗi chia 0 từ Excel)
#xử lý lỗi 
df['AP Ratio'] = df['AP Ratio'].replace('#DIV/0!', np.nan) # Bước 1: thay lỗi div bằng NaN 
 
# Bước 2: Convert sang float
df['AP Ratio'] = pd.to_numeric(df['AP Ratio'], errors='coerce')
 
# Bước 3: Điền NaN bằng giá trị trung vị (median) — ít bị ảnh hưởng bởi outlier
median_val = df['AP Ratio'].median()
df['AP Ratio'] = df['AP Ratio'].fillna(median_val)
 
print("=== SAU KHI SỬA ===")
print(f"Kiểu dữ liệu mới : {df['AP Ratio'].dtype}")
print(f"Số NaN còn lại   : {df['AP Ratio'].isnull().sum()}")
print(f"Đã điền bằng median = {median_val:.4f}")
print(f"\n Thống kê mô tả:")
print(df['AP Ratio'].describe())

Kiểu dữ liệu: str
Số giá trị không convert được: 416
Các giá trị lỗi:
AP Ratio
#DIV/0!    416
Name: count, dtype: int64
=== SAU KHI SỬA ===
Kiểu dữ liệu mới : float64
Số NaN còn lại   : 0
Đã điền bằng median = 2.5180

 Thống kê mô tả:
count    4608.000000
mean        4.597917
std        17.138637
min         0.000000
25%         1.406238
50%         2.518030
75%         4.344176
max       951.216667
Name: AP Ratio, dtype: float64

In [21]:
print(" TRƯỚC KHI SỬA ")
print("Tên cột có khoảng trắng:")
for col in df.columns:
    if ' ' in col:
        print(f"    '{col}'")
 #Vấn đề: `AP Ratio`, `Avg Humidity`, `Crop Name` có dấu cách _ gây lỗi khi dùng `df.column_name
#xử lý
# ── Xử lý lỗi ──
df.columns = df.columns.str.strip().str.replace(' ', '_')
 
print("=== SAU KHI SỬA ===")
print("Tất cả tên cột:")
print(list(df.columns))

 TRƯỚC KHI SỬA
Tên cột có khoảng trắng:
    'AP Ratio'
    'Avg Humidity'
    'Crop Name'
=== SAU KHI SỬA ===
Tất cả tên cột:
['FPAR', 'Avg_Salinity_Index', 'EVI', 'Rain_Temp_Ratio', 'Rainfall', 'Wind_Mean', 'Temp_Min', 'Wind_Max', 'Temp_Max', 'District', 'Clay', 'LAI', 'Nitrogen', 'Soil_Moisture_mm', 'pH', 'LST_Kelvin', 'Dominant_Soil_Texture', 'AP_Ratio', 'Temp_Mean', 'Avg_Humidity', 'Heat_Stress_Days', 'Silt', 'Growth', 'CN_Ratio', 'Crop_Name', 'Organic_Carbon', 'Transplant', 'Season', 'NDVI_Season_Mean']

In [22]:
print(df['Dominant_Soil_Texture'].value_counts())
#Vấn đề: Tên loại đất chứa chú thích tiếng Việt trong ngoặc
#xử lý 
import re
df['Dominant_Soil_Texture'] = df['Dominant_Soil_Texture'].apply(
    lambda x: re.sub(r'\\s*\\(.*?\\)', '', str(x)).strip()
)
 
print(" SAU KHI SỬA ")
print(df['Dominant_Soil_Texture'].value_counts())
print("\n Đã chuẩn hoá tên loại đất!")

Dominant_Soil_Texture
Loamy (Thịt/Phù sa)    4536
Clayey (Sét)             72
Name: count, dtype: int64
 SAU KHI SỬA
Dominant_Soil_Texture
Loamy (Thịt/Phù sa)    4536
Clayey (Sét)             72
Name: count, dtype: int64

 Đã chuẩn hoá tên loại đất!

In [23]:
# Tìm giá trị có 2 khoảng trắng liên tiếp
double_space = df['Growth'].str.contains('  ', na=False)
print("Giá trị có 2+ khoảng trắng:", df[double_space]['Growth'].value_counts().to_dict())
 
# Tìm giá trị viết thường (ví dụ 'july' thay vì 'July')
bad_case = df['Growth'].str.contains('[a-z]o [a-z]', na=False)  # "to july"
print("\n Giá trị viết thường bất thường:")
print(df[bad_case]['Growth'].value_counts().to_dict())
#Vấn đề: `'Jan  to  March'` (2 khoảng trắng) vs `'Dec to March'` (1 khoảng trắng), `'April to july'` (chữ j thường)
#xử lý
# Bước 1: Loại khoảng trắng thừa (collapse multiple spaces)
df['Growth'] = df['Growth'].str.split().str.join(' ')
# Bước 2: Chuẩn hoá chữ hoa/thường — Title Case
df['Growth'] = df['Growth'].str.title()
 
print(" SAU KHI SỬA ")
print(df['Growth'].value_counts())
print("\n Đã chuẩn hoá cột Growth!")

Giá trị có 2+ khoảng trắng: {'Jan  to  March': 128, 'Nov  to  Feb': 64, 'July to  Oct': 64}

 Giá trị viết thường bất thường:
{'No need to do': 640, 'April to july': 64}
 SAU KHI SỬA
Growth
No Need To Do     640
Nov To March      384
June To August    320
Nov To Feb        320
Oct To Nov        320
April To Aug      256
Sep To Jan        192
Sep To Oct        192
Jan To March      128
Dec To March      128
April To July     128
Oct To Dec        128
Nov To Jan        128
Jan To Jan        128
Aug To Jan        128
July To August    128
May To June       128
March To July      64
Nov To Aug         64
Dec To Jan         64
Oct To Jan         64
Dec To Feb         64
March To April     64
May To July        64
Sep To May         64
April To May       64
March To May       64
July To Nov        64
July To Oct        64
May To Sep         64
Name: count, dtype: int64

 Đã chuẩn hoá cột Growth!

In [24]:

print("Các giá trị unique:")
print(sorted(df['Transplant'].unique()))
print(f"\n Tổng: {df['Transplant'].nunique()} giá trị — nhưng thực ra chỉ có 12 tháng!")
#Vấn đề: Cùng tháng nhưng có 2 cách viết — `Aug` và `August`, `Dec` và `December`…
#xử lý 
month_map = {
    'Jan': 'January',   'Feb': 'February', 'Mar': 'March',
    'Apr': 'April',     'Jun': 'June',     'Jul': 'July',
    'Aug': 'August',    'Sep': 'September','Oct': 'October',
    'Nov': 'November',  'Dec': 'December'
}
df['Transplant'] = df['Transplant'].replace(month_map)
 

print("Các giá trị unique:")
print(sorted(df['Transplant'].unique()))
print(f"\n Đã chuẩn hoá — còn {df['Transplant'].nunique()} giá trị duy nhất!")

Các giá trị unique:
['April', 'Aug', 'August', 'Dec', 'December', 'Feb', 'February', 'Jan', 'January', 'July', 'June', 'March', 'May', 'Nov', 'November', 'Oct', 'October', 'Sep', 'September']

 Tổng: 19 giá trị — nhưng thực ra chỉ có 12 tháng!
Các giá trị unique:
['April', 'August', 'December', 'February', 'January', 'July', 'June', 'March', 'May', 'November', 'October', 'September']

 Đã chuẩn hoá — còn 12 giá trị duy nhất!

In [25]:
n_neg = (df['NDVI_Season_Mean'] < 0).sum()
print(" TRƯỚC KHI SỬA ")
print(f"Số giá trị NDVI âm: {n_neg}")
print(df[df['NDVI_Season_Mean'] < 0]['NDVI_Season_Mean'].describe())
#Vấn đề: NDVI lý thuyết thuộc [-1, 1], nhưng giá trị âm gần 0 thường là nhiễu cảm biến → clip về 0
#xử lý
# Clip về 0 vì giá trị âm rất nhỏ (≈ -0.0017) → nhiễu đo lường
df['NDVI_Season_Mean'] = df['NDVI_Season_Mean'].clip(lower=0)
 
print(" SAU KHI SỬA ")
print(f"Số giá trị NDVI < 0 còn lại: {(df['NDVI_Season_Mean'] < 0).sum()}")
print(f"NDVI min: {df['NDVI_Season_Mean'].min():.6f}")
print("\n Đã xử lý giá trị NDVI âm!")

 TRƯỚC KHI SỬA
Số giá trị NDVI âm: 24
count    24.000000
mean     -0.001671
std       0.000000
min      -0.001671
25%      -0.001671
50%      -0.001671
75%      -0.001671
max      -0.001671
Name: NDVI_Season_Mean, dtype: float64
 SAU KHI SỬA
Số giá trị NDVI < 0 còn lại: 0
NDVI min: 0.000000

 Đã xử lý giá trị NDVI âm!

In [26]:
# 1. Ép kiểu số an toàn cho các cột đo lường khí hậu
numeric_fix_cols = ['Avg Temp', 'Avg Humidity', 'Max Temp', 'Min Temp', 'Rainfall', 'Wind_Mean', 'pH']
for col in numeric_fix_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].fillna(df[col].mean())

# 2. Hiệu chỉnh hệ số tỷ lệ cho FPAR
if 'FPAR' in df.columns:
    df['FPAR'] = df['FPAR'] * 0.1

# 3. Chuyển đổi LST từ Kelvin sang độ C
if 'LST_Kelvin' in df.columns:
    df['LST_C'] = df['LST_Kelvin'] - 273.15
    df = df.drop(columns=['LST_Kelvin'])

# 4. Chuẩn hóa tổng tỷ lệ thành phần đất (Clay + Sand + Silt = 100%)
soil_parts = ['Clay', 'Sand', 'Silt']
if all(col in df.columns for col in soil_parts):
    soil_sum = df[soil_parts].sum(axis=1)
    df[soil_parts] = df[soil_parts].div(soil_sum, axis=0) * 100

# 5. Đảo ngược lỗi hoán đổi cột độ ẩm nếu có
if 'Max Relative Humidity' in df.columns and 'Min Relative Humidity' in df.columns:
    # Đảm bảo Max luôn lớn hơn hoặc bằng Min
    mask = df['Max Relative Humidity'] < df['Min Relative Humidity']
    df.loc[mask, ['Min Relative Humidity', 'Max Relative Humidity']] = df.loc[mask, ['Max Relative Humidity', 'Min Relative Humidity']].values

print("Hoàn thành hiệu chỉnh logic và chỉ số vật lý.")

Hoàn thành hiệu chỉnh logic và chỉ số vật lý.

In [27]:
#Phát hiện và xử lý Outlier (IQR Method)
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
 
print(" PHÁT HIỆN OUTLIER ")
print(f"{'Cột':<25} {'Số outlier':>12} {'Tỷ lệ (%)':>12}")
print("-" * 52)
 
outlier_cols = []
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    n_out = ((df[col] < lower) | (df[col] > upper)).sum()
    pct = round(n_out / len(df) * 100, 2)
    if n_out > 0:
        outlier_cols.append(col)
        print(f"{col:<25} {n_out:>12} {pct:>11}%")
 
print(f"\nTổng số cột có outlier: {len(outlier_cols)}")
#xử lý outlier

df_cleaned = df.copy()
 
for col in outlier_cols:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df_cleaned[col] = df_cleaned[col].clip(lower=lower, upper=upper)
 
print("=== SAU KHI XỬ LÝ OUTLIER ===")
# Kiểm tra lại
total_out = 0
for col in outlier_cols:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1
    n = ((df_cleaned[col] < Q1 - 1.5*IQR) | (df_cleaned[col] > Q3 + 1.5*IQR)).sum()
    total_out += n
 
print(f"Tổng outlier còn lại: {total_out}")

 PHÁT HIỆN OUTLIER
Cột                         Số outlier    Tỷ lệ (%)
----------------------------------------------------
FPAR                               168        3.65%
EVI                                184        3.99%
Rain_Temp_Ratio                     24        0.52%
Rainfall                            24        0.52%
Wind_Mean                           24        0.52%
Wind_Max                           256        5.56%
LAI                                296        6.42%
Nitrogen                           360        7.81%
pH                                 144        3.12%
AP_Ratio                           443        9.61%
Avg_Humidity                       256        5.56%
Heat_Stress_Days                   768       16.67%
Silt                               144        3.12%
CN_Ratio                            72        1.56%
Organic_Carbon                     144        3.12%
NDVI_Season_Mean                   116        2.52%

Tổng số cột có outlier: 16
=== SAU KHI XỬ LÝ OUTLIER ===
Tổng outlier còn lại: 0

In [28]:
output_file = 'Agri_Data_Cleaned.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"File dữ liệu sạch giữ nguyên toàn bộ các feature đã được xuất tại: {output_file}")

File dữ liệu sạch giữ nguyên toàn bộ các feature đã được xuất tại: Agri_Data_Cleaned.csv